name: jewellery_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1


  cupertino_icons: ^1.0.6
  path: ^1.9.0
  sqflite: ^2.3.2
  sqflite_common_ffi_web: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/home/
    - assets/images/
    - assets/Necklaces/
    - assets/Rings/
    - assets/Earings/
    - assets/Bangles/
    - assets/Nath/
    - assets/Payal/








  